spring:
  application:
    name: spring
  datasource:
    url: jdbc:postgresql://147.45.151.57:5432/mkustov
    username: mkustov
    schema: animals
    password: mkustov1
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      default_schema: animals
  liquibase:
    change-log: classpath:liquibase/changelog.yml
